### ISSUE TITLE
Timeout error?

### ISSUE THREAD

**Issue by Argorate** [watir/watir-rails#21] opened 2018-08-04 22:54 UTC
I would try your gem to test Watir lib, I add "gem 'watir-rails'" to my gem file, do bundle install
and start app on route with this action controller :+1: 

def index
    browser = Watir::Browser.new
    browser.goto 'http://www.googe.com'
end

but it send timeout error : "Rails Rack application timed out during boot"

what's wrong?

**Comment by Argorate** [comment] 2018-08-05 13:07
It mean that works only in test ENV? why that?

**Comment by jarmo** [comment] 2018-08-05 13:27
As stated already - watir-rails is meant to help testing a Rails application and not to be used within Rails application. The reason is that it start Rails instance automatically for testing when tests are running and this might cause a problem when trying to do it within an already running Rails instance. And there's no point of doing that. And I don't know what you are trying to solve there exactly, but it's always fishy when trying to run Watir code inside of a controller's action - are you sure that a regular non-rails script would not be enough for your needs?

Closing this since this is not directly an issue with watir-rails, but is caused by misusing it.

**Closed by jarmo** 2018-08-05 13:27 UTC
